paths:
  base_data_dir: "./data"
  raw_dir: "./data/raw"
  processed_dir: "./data/processed"

sources:
  csv_example:
    type: "csv"
    path: "./data/input/google_trends_ai.csv"

  news_ai:
      type: "rss"
      url: "https://news.google.com/rss/search?q=intelligence+artificielle&hl=fr&gl=FR&ceid=FR:fr"

database:
  driver: "postgresql"
  host: "localhost"
  port: 5432
  user: "datalake_user"
  password: "datalake_pass"
  db: "datalake_db"
